# These are supported funding model platforms

github: StaniB88
# ko_fi: # Uncomment and add username if you have Ko-fi
# buy_me_a_coffee: # Uncomment and add username if you have BMC
# patreon: # Uncomment and add username if you have Patreon
# custom: ['https://your-custom-link.com'] # Add custom donation links
